package com.zfsoft.newmobile.login.CXFService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-04-24T15:30:21.736+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", name = "IWSSerServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSSerServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "votelike", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Votelike")
    @WebMethod
    @ResponseWrapper(localName = "votelikeResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VotelikeResponse")
    public java.lang.String votelike(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getocdetail", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Getocdetail")
    @WebMethod
    @ResponseWrapper(localName = "getocdetailResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetocdetailResponse")
    public java.lang.String getocdetail(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in6
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMyMemoList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMyMemoList")
    @WebMethod
    @ResponseWrapper(localName = "getMyMemoListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMyMemoListResponse")
    public java.lang.String getMyMemoList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMobileAppType", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMobileAppType")
    @WebMethod
    @ResponseWrapper(localName = "getMobileAppTypeResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMobileAppTypeResponse")
    public java.lang.String getMobileAppType();

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getAllXtYwByUser", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetAllXtYwByUser")
    @WebMethod
    @ResponseWrapper(localName = "getAllXtYwByUserResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetAllXtYwByUserResponse")
    public java.lang.String getAllXtYwByUser(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "submitMemoCatalogList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitMemoCatalogList")
    @WebMethod
    @ResponseWrapper(localName = "submitMemoCatalogListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitMemoCatalogListResponse")
    public java.lang.String submitMemoCatalogList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getSchoolSuggestList", targetNamespace = "http://service.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetSchoolSuggestList")
    @WebMethod
    @ResponseWrapper(localName = "getSchoolSuggestListResponse", targetNamespace = "http://service.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetSchoolSuggestListResponse")
    public java.lang.String getSchoolSuggestList(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.webservices.mobile.zfsoft.com/")
        java.lang.String in5
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "myPortalFunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.MyPortalFunction")
    @WebMethod
    @ResponseWrapper(localName = "myPortalFunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.MyPortalFunctionResponse")
    public java.lang.String myPortalFunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "uploadMyPicture", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.UploadMyPicture")
    @WebMethod
    @ResponseWrapper(localName = "uploadMyPictureResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.UploadMyPictureResponse")
    public java.lang.String uploadMyPicture(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        byte[] in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNewsTab", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsTab")
    @WebMethod
    @ResponseWrapper(localName = "getNewsTabResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsTabResponse")
    public java.lang.String getNewsTab(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "digitalArchivesDpList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DigitalArchivesDpList")
    @WebMethod
    @ResponseWrapper(localName = "digitalArchivesDpListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DigitalArchivesDpListResponse")
    public java.lang.String digitalArchivesDpList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getWeiBoList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetWeiBoList")
    @WebMethod
    @ResponseWrapper(localName = "getWeiBoListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetWeiBoListResponse")
    public java.lang.String getWeiBoList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getLossObjectList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetLossObjectList")
    @WebMethod
    @ResponseWrapper(localName = "getLossObjectListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetLossObjectListResponse")
    public java.lang.String getLossObjectList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in4
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "CommonAllFunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonAllFunction")
    @WebMethod(operationName = "CommonAllFunction")
    @ResponseWrapper(localName = "CommonAllFunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonAllFunctionResponse")
    public java.lang.String commonAllFunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "callInterface", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CallInterface")
    @WebMethod
    @ResponseWrapper(localName = "callInterfaceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CallInterfaceResponse")
    public java.lang.String callInterface(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNewsByCategory", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsByCategory")
    @WebMethod
    @ResponseWrapper(localName = "getNewsByCategoryResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsByCategoryResponse")
    public java.lang.String getNewsByCategory(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNewsList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsList")
    @WebMethod
    @ResponseWrapper(localName = "getNewsListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNewsListResponse")
    public java.lang.String getNewsList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "votelist", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Votelist")
    @WebMethod
    @ResponseWrapper(localName = "votelistResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VotelistResponse")
    public java.lang.String votelist(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "digitalArchivesPersonnelList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DigitalArchivesPersonnelList")
    @WebMethod
    @ResponseWrapper(localName = "digitalArchivesPersonnelListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DigitalArchivesPersonnelListResponse")
    public java.lang.String digitalArchivesPersonnelList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in5
    );

    @RequestWrapper(localName = "modifyFrequentlyService", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.ModifyFrequentlyService")
    @WebMethod
    @ResponseWrapper(localName = "modifyFrequentlyServiceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.ModifyFrequentlyServiceResponse")
    public void modifyFrequentlyService(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in3
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "personDocumentInformation", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PersonDocumentInformation")
    @WebMethod
    @ResponseWrapper(localName = "personDocumentInformationResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PersonDocumentInformationResponse")
    public java.lang.String personDocumentInformation(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMhRecommendPage", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMhRecommendPage")
    @WebMethod
    @ResponseWrapper(localName = "getMhRecommendPageResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMhRecommendPageResponse")
    public java.lang.String getMhRecommendPage(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "deleteThirdParty", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteThirdParty")
    @WebMethod
    @ResponseWrapper(localName = "deleteThirdPartyResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteThirdPartyResponse")
    public java.lang.String deleteThirdParty(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "publishLossObject", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PublishLossObject")
    @WebMethod
    @ResponseWrapper(localName = "publishLossObjectResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PublishLossObjectResponse")
    public java.lang.String publishLossObject(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "submitSuggestion", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitSuggestion")
    @WebMethod
    @ResponseWrapper(localName = "submitSuggestionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitSuggestionResponse")
    public java.lang.String submitSuggestion(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "voteRanklist", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VoteRanklist")
    @WebMethod
    @ResponseWrapper(localName = "voteRanklistResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VoteRanklistResponse")
    public java.lang.String voteRanklist(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNoticeInfo", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeInfo")
    @WebMethod
    @ResponseWrapper(localName = "getNoticeInfoResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeInfoResponse")
    public java.lang.String getNoticeInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "SubmitCommonFunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitCommonFunction")
    @WebMethod(operationName = "SubmitCommonFunction")
    @ResponseWrapper(localName = "SubmitCommonFunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitCommonFunctionResponse")
    public java.lang.String submitCommonFunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        boolean in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getUserTimeLine", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetUserTimeLine")
    @WebMethod
    @ResponseWrapper(localName = "getUserTimeLineResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetUserTimeLineResponse")
    public java.lang.String getUserTimeLine(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        long in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNoticeList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeList")
    @WebMethod
    @ResponseWrapper(localName = "getNoticeListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeListResponse")
    public java.lang.String getNoticeList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetTicket")
    @WebMethod
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetTicketResponse")
    public java.lang.String getTicket(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMhRecommendPage1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMhRecommendPage1")
    @WebMethod
    @ResponseWrapper(localName = "getMhRecommendPage1Response", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMhRecommendPage1Response")
    public java.lang.String getMhRecommendPage1(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMapList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMapList")
    @WebMethod
    @ResponseWrapper(localName = "getMapListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMapListResponse")
    public java.lang.String getMapList();

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "deleteMyMemoList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteMyMemoList")
    @WebMethod
    @ResponseWrapper(localName = "deleteMyMemoListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteMyMemoListResponse")
    public java.lang.String deleteMyMemoList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "submitThirdParty", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitThirdParty")
    @WebMethod
    @ResponseWrapper(localName = "submitThirdPartyResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitThirdPartyResponse")
    public java.lang.String submitThirdParty(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getQRcode", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetQRcode")
    @WebMethod
    @ResponseWrapper(localName = "getQRcodeResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetQRcodeResponse")
    public java.lang.String getQRcode();

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getTermWeek", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetTermWeek")
    @WebMethod
    @ResponseWrapper(localName = "getTermWeekResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetTermWeekResponse")
    public java.lang.String getTermWeek(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );


    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "insertVisitsToZFByFwbm", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.InsertVisitsToZFByFwbm")
    @WebMethod
    @ResponseWrapper(localName = "insertVisitsToZFByFwbmResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.InsertVisitsToZFByFwbmResponse")
    public java.lang.String insertVisitsToZFByFwbm(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );


    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "thirdPartyLogin", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.ThirdPartyLogin")
    @WebMethod
    @ResponseWrapper(localName = "thirdPartyLoginResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.ThirdPartyLoginResponse")
    public java.lang.String thirdPartyLogin(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getNoticeListNewTableType", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeListNewTableType")
    @WebMethod
    @ResponseWrapper(localName = "getNoticeListNewTableTypeResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetNoticeListNewTableTypeResponse")
    public java.lang.String getNoticeListNewTableType();

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getPortalInfo", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetPortalInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPortalInfoResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetPortalInfoResponse")
    public java.lang.String getPortalInfo(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "CommonBrushFunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonBrushFunction")
    @WebMethod(operationName = "CommonBrushFunction")
    @ResponseWrapper(localName = "CommonBrushFunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonBrushFunctionResponse")
    public java.lang.String commonBrushFunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getThirdPartyList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetThirdPartyList")
    @WebMethod
    @ResponseWrapper(localName = "getThirdPartyListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetThirdPartyListResponse")
    public java.lang.String getThirdPartyList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getExamList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetExamList")
    @WebMethod
    @ResponseWrapper(localName = "getExamListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetExamListResponse")
    public java.lang.String getExamList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        int in2
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMemoCatalogList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMemoCatalogList")
    @WebMethod
    @ResponseWrapper(localName = "getMemoCatalogListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMemoCatalogListResponse")
    public java.lang.String getMemoCatalogList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "sign", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Sign")
    @WebMethod
    @ResponseWrapper(localName = "signResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SignResponse")
    public java.lang.String sign(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "visitsByFwbm", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VisitsByFwbm")
    @WebMethod
    @ResponseWrapper(localName = "visitsByFwbmResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VisitsByFwbmResponse")
    public java.lang.String visitsByFwbm(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "Commonfunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Commonfunction")
    @WebMethod(operationName = "Commonfunction")
    @ResponseWrapper(localName = "CommonfunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonfunctionResponse")
    public java.lang.String commonfunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getMyPicturePath", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMyPicturePath")
    @WebMethod
    @ResponseWrapper(localName = "getMyPicturePathResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetMyPicturePathResponse")
    public java.lang.String getMyPicturePath(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "versionCompare", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VersionCompare")
    @WebMethod
    @ResponseWrapper(localName = "versionCompareResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.VersionCompareResponse")
    public java.lang.String versionCompare(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in6
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "personDocumentInformationList", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PersonDocumentInformationList")
    @WebMethod
    @ResponseWrapper(localName = "personDocumentInformationListResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.PersonDocumentInformationListResponse")
    public java.lang.String personDocumentInformationList(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getocbalance", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.Getocbalance")
    @WebMethod
    @ResponseWrapper(localName = "getocbalanceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetocbalanceResponse")
    public java.lang.String getocbalance(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "submitExam", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitExam")
    @WebMethod
    @ResponseWrapper(localName = "submitExamResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitExamResponse")
    public java.lang.String submitExam(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "insertFrequentlyService", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.InsertFrequentlyService")
    @WebMethod
    @ResponseWrapper(localName = "insertFrequentlyServiceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.InsertFrequentlyServiceResponse")
    public java.lang.String insertFrequentlyService(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        boolean in3
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "CommonOtherFunction", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonOtherFunction")
    @WebMethod(operationName = "CommonOtherFunction")
    @ResponseWrapper(localName = "CommonOtherFunctionResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.CommonOtherFunctionResponse")
    public java.lang.String commonOtherFunction(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "submitExamAnswer", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitExamAnswer")
    @WebMethod
    @ResponseWrapper(localName = "submitExamAnswerResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.SubmitExamAnswerResponse")
    public java.lang.String submitExamAnswer(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "getCommonService", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetCommonService")
    @WebMethod
    @ResponseWrapper(localName = "getCommonServiceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.GetCommonServiceResponse")
    public java.lang.String getCommonService();

    @WebResult(name = "out", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
    @RequestWrapper(localName = "deleteFrequentlyService", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteFrequentlyService")
    @WebMethod
    @ResponseWrapper(localName = "deleteFrequentlyServiceResponse", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/", className = "com.newmobile.login.CXFService.DeleteFrequentlyServiceResponse")
    public java.lang.String deleteFrequentlyService(
        @WebParam(name = "in0", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
        java.lang.String in2
    );
}
