package com.zfsoft.xg.xg.CXFService.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.zfsoft.xg.xg.CXFService.IxgService;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-10-30T10:05:24.312+08:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "XgServiceImplService",
                  wsdlLocation = "http://10.71.32.70:8089/zfxg-ws-web/xgService?wsdl",
                  targetNamespace = "http://impl.service.xg.xgws.zfsoft.com/")
public class XgServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.xg.xgws.zfsoft.com/", "XgServiceImplService");
    public final static QName XgServiceImplPort = new QName("http://impl.service.xg.xgws.zfsoft.com/", "XgServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.71.32.70:8089/zfxg-ws-web/xgService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XgServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.71.32.70:8089/zfxg-ws-web/xgService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XgServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XgServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XgServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
/*    public XgServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XgServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XgServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     *
     * @return
     *     returns IxgService
     */
    @WebEndpoint(name = "XgServiceImplPort")
    public IxgService getXgServiceImplPort() {
        return super.getPort(XgServiceImplPort, IxgService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IxgService
     */
    @WebEndpoint(name = "XgServiceImplPort")
    public IxgService getXgServiceImplPort(WebServiceFeature... features) {
        return super.getPort(XgServiceImplPort, IxgService.class, features);
    }

}
