
package com.zfsoft.backMh.recommend.CXFService.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-31T16:38:25.671+08:00
 * Generated source version: 2.6.0
 *
 */

public class IRecommendXmlService_RecommendXmlServicePort_Server{

    protected IRecommendXmlService_RecommendXmlServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IRecommendXmlServiceImpl();
        String address = "http://10.71.32.205:8888/zfmcmh/webservices/mhrecommend/RecommendXmlService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new IRecommendXmlService_RecommendXmlServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
