
package com.zfsoft.backMh.recommend.CXFService.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.zfsoft.backMh.recommend.CXFService.service.impl.RecommendXmlServiceService;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-31T16:38:25.625+08:00
 * Generated source version: 2.6.0
 *
 */
public final class IRecommendXmlService_RecommendXmlServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.mhrecommend.logic.webservice.general.zfsoft.com/", "RecommendXmlServiceService");

    private IRecommendXmlService_RecommendXmlServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecommendXmlServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RecommendXmlServiceService ss = new RecommendXmlServiceService(wsdlURL, SERVICE_NAME);
        IRecommendXmlService port = ss.getRecommendXmlServicePort();

        {
        System.out.println("Invoking getRecommendInfo...");
        java.lang.String _getRecommendInfo_id = "";
        java.lang.String _getRecommendInfo__return = port.getRecommendInfo(_getRecommendInfo_id);
        System.out.println("getRecommendInfo.result=" + _getRecommendInfo__return);


        }
        {
        System.out.println("Invoking getMhRecommendList...");
        int _getMhRecommendList_start = 0;
        int _getMhRecommendList_size = 0;
        java.lang.String _getMhRecommendList__return = port.getMhRecommendList(_getMhRecommendList_start, _getMhRecommendList_size);
        System.out.println("getMhRecommendList.result=" + _getMhRecommendList__return);


        }
        {
        System.out.println("Invoking getMhRecommendPage...");
        int _getMhRecommendPage_start = 0;
        int _getMhRecommendPage_size = 0;
        java.lang.String _getMhRecommendPage__return = port.getMhRecommendPage(_getMhRecommendPage_start, _getMhRecommendPage_size);
        System.out.println("getMhRecommendPage.result=" + _getMhRecommendPage__return);


        }

        System.exit(0);
    }

}
