package com.zfsoft.backMh.recommend.CXFService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-31T16:38:25.656+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", name = "IRecommendXmlService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRecommendXmlService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRecommendInfo", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetRecommendInfo")
    @WebMethod
    @ResponseWrapper(localName = "getRecommendInfoResponse", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetRecommendInfoResponse")
    public java.lang.String getRecommendInfo(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMhRecommendList", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetMhRecommendList")
    @WebMethod
    @ResponseWrapper(localName = "getMhRecommendListResponse", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetMhRecommendListResponse")
    public java.lang.String getMhRecommendList(
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "size", targetNamespace = "")
        int size
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMhRecommendPage", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetMhRecommendPage")
    @WebMethod
    @ResponseWrapper(localName = "getMhRecommendPageResponse", targetNamespace = "http://service.mhrecommend.logic.webservice.general.zfsoft.com/", className = "com.backMh.recommend.CXFService.service.GetMhRecommendPageResponse")
    public java.lang.String getMhRecommendPage(
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "size", targetNamespace = "")
        int size
    );
}
