
package com.zfsoft.backMh.notice.CXFService.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.zfsoft.backMh.notice.CXFService.service.impl.NoticeXmlServiceService;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T10:15:37.015+08:00
 * Generated source version: 2.5.2
 *
 */
public final class INoticeXmlService_NoticeXmlServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.notice.sys.webservice.general.zfsoft.com/", "NoticeXmlServiceService");

    private INoticeXmlService_NoticeXmlServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = NoticeXmlServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        NoticeXmlServiceService ss = new NoticeXmlServiceService(wsdlURL, SERVICE_NAME);
        INoticeXmlService port = ss.getNoticeXmlServicePort();

        {
        System.out.println("Invoking getIndexNoticeListXml...");
        int _getIndexNoticeListXml_topCount = 0;
        java.lang.String _getIndexNoticeListXml__return = port.getIndexNoticeListXml(_getIndexNoticeListXml_topCount);
        System.out.println("getIndexNoticeListXml.result=" + _getIndexNoticeListXml__return);


        }
        {
        System.out.println("Invoking getNoticeInfo...");
        java.lang.String _getNoticeInfo_id = "";
        java.lang.String _getNoticeInfo__return = port.getNoticeInfo(_getNoticeInfo_id);
        System.out.println("getNoticeInfo.result=" + _getNoticeInfo__return);


        }

        System.exit(0);
    }

}
