
package com.zfsoft.backMh.notice.CXFService.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T10:15:37.046+08:00
 * Generated source version: 2.5.2
 *
 */

public class INoticeXmlService_NoticeXmlServicePort_Server{

    protected INoticeXmlService_NoticeXmlServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new INoticeXmlServiceImpl();
        String address = "http://10.71.19.191:9992/zfmcmh/webservices/notice/NoticeXmlService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new INoticeXmlService_NoticeXmlServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
