package com.zfsoft.backMh.notice.CXFService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T10:15:37.046+08:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://service.notice.sys.webservice.general.zfsoft.com/", name = "INoticeXmlService")
@XmlSeeAlso({ObjectFactory.class})
public interface INoticeXmlService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIndexNoticeListXml", targetNamespace = "http://service.notice.sys.webservice.general.zfsoft.com/", className = "com.backMh.notice.CXFService.service.GetIndexNoticeListXml")
    @WebMethod
    @ResponseWrapper(localName = "getIndexNoticeListXmlResponse", targetNamespace = "http://service.notice.sys.webservice.general.zfsoft.com/", className = "com.backMh.notice.CXFService.service.GetIndexNoticeListXmlResponse")
    public java.lang.String getIndexNoticeListXml(
        @WebParam(name = "topCount", targetNamespace = "")
        int topCount
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNoticeInfo", targetNamespace = "http://service.notice.sys.webservice.general.zfsoft.com/", className = "com.backMh.notice.CXFService.service.GetNoticeInfo")
    @WebMethod
    @ResponseWrapper(localName = "getNoticeInfoResponse", targetNamespace = "http://service.notice.sys.webservice.general.zfsoft.com/", className = "com.backMh.notice.CXFService.service.GetNoticeInfoResponse")
    public java.lang.String getNoticeInfo(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
