
package com.zfsoft.backMh.schoolsights.CXFService.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.zfsoft.backMh.schoolsights.CXFService.service.impl.SchoolsightsXmlServiceService;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:09:42.421+08:00
 * Generated source version: 2.5.2
 *
 */
public final class ISchoolsightsXmlService_SchoolsightsXmlServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.schoolsights.logic.webservice.general.zfsoft.com/", "SchoolsightsXmlServiceService");

    private ISchoolsightsXmlService_SchoolsightsXmlServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SchoolsightsXmlServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SchoolsightsXmlServiceService ss = new SchoolsightsXmlServiceService(wsdlURL, SERVICE_NAME);
        ISchoolsightsXmlService port = ss.getSchoolsightsXmlServicePort();

        {
        System.out.println("Invoking getAllSchoolTypeList...");
        java.lang.String _getAllSchoolTypeList__return = port.getAllSchoolTypeList();
        System.out.println("getAllSchoolTypeList.result=" + _getAllSchoolTypeList__return);


        }
        {
        System.out.println("Invoking getTypeSchoolSightsPageList...");
        java.lang.String _getTypeSchoolSightsPageList_tid = "";
        int _getTypeSchoolSightsPageList_start = 0;
        int _getTypeSchoolSightsPageList_size = 0;
        java.lang.String _getTypeSchoolSightsPageList__return = port.getTypeSchoolSightsPageList(_getTypeSchoolSightsPageList_tid, _getTypeSchoolSightsPageList_start, _getTypeSchoolSightsPageList_size);
        System.out.println("getTypeSchoolSightsPageList.result=" + _getTypeSchoolSightsPageList__return);


        }

        System.exit(0);
    }

}
