package com.zfsoft.backMh.schoolsights.CXFService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:09:42.453+08:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", name = "ISchoolsightsXmlService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISchoolsightsXmlService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllSchoolTypeList", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetAllSchoolTypeList")
    @WebMethod
    @ResponseWrapper(localName = "getAllSchoolTypeListResponse", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetAllSchoolTypeListResponse")
    public java.lang.String getAllSchoolTypeList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTypeSchoolSightsPageList", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetTypeSchoolSightsPageList")
    @WebMethod
    @ResponseWrapper(localName = "getTypeSchoolSightsPageListResponse", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetTypeSchoolSightsPageListResponse")
    public java.lang.String getTypeSchoolSightsPageList(
        @WebParam(name = "tid", targetNamespace = "")
        java.lang.String tid,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "size", targetNamespace = "")
        int size
    );
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTypeSchoolSightsPageListNew", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetTypeSchoolSightsPageListNew")
    @WebMethod
    @ResponseWrapper(localName = "getTypeSchoolSightsPageListNewResponse", targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/", className = "com.backMh.schoolsights.CXFService.service.GetTypeSchoolSightsPageListNewResponse")
    public java.lang.String getTypeSchoolSightsPageListNew(
        @WebParam(name = "tid", targetNamespace = "")
        java.lang.String tid,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "size", targetNamespace = "")
        int size
    );
}
