
package com.zfsoft.backMh.schoolsights.CXFService.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:09:42.468+08:00
 * Generated source version: 2.5.2
 *
 */

public class ISchoolsightsXmlService_SchoolsightsXmlServicePort_Server{

    protected ISchoolsightsXmlService_SchoolsightsXmlServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ISchoolsightsXmlServiceImpl();
        String address = "http://10.71.19.191:9992/zfmcmh/webservices/schoolsights/SchoolsightsXmlService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ISchoolsightsXmlService_SchoolsightsXmlServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
