
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zfsoft.backMh.schoolintroduce.CXFServe.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-21T13:47:33.125+08:00
 * Generated source version: 2.6.0
 *
 */

@javax.jws.WebService(
                      serviceName = "SIntroduceXmlServiceService",
                      portName = "SIntroduceXmlServicePort",
                      targetNamespace = "http://impl.service.schoolintroduce.logic.webservice.general.zfsoft.com/",
                      wsdlLocation = "http://localhost:8888/zfmmh_manager/webservices/sIntroduce/SIntroduceXmlService?wsdl",
                      endpointInterface = "com.backMh.schoolintroduce.CXFServe.service.ISIntroduceXmlService")

public class ISIntroduceXmlServiceImpl implements ISIntroduceXmlService {

    private static final Logger LOG = Logger.getLogger(ISIntroduceXmlServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.schoolintroduce.service.ISIntroduceXmlService#getRootSchoolIntroduceTypeList(*
     */
    public java.lang.String getRootSchoolIntroduceTypeList() {
        LOG.info("Executing operation getRootSchoolIntroduceTypeList");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.schoolintroduce.service.ISIntroduceXmlService#getSchoolIntroduceById(java.lang.String  tid )*
     */
    public java.lang.String getSchoolIntroduceById(java.lang.String tid) {
        LOG.info("Executing operation getSchoolIntroduceById");
        System.out.println(tid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.schoolintroduce.service.ISIntroduceXmlService#getSchoolIntroduceTitleList(java.lang.String  id ,)int  start ,)int  size )*
     */
    public java.lang.String getSchoolIntroduceTitleList(java.lang.String id,int start,int size) {
        LOG.info("Executing operation getSchoolIntroduceTitleList");
        System.out.println(id);
        System.out.println(start);
        System.out.println(size);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
