package com.zfsoft.newmobile.login.CXFService.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.zfsoft.newmobile.login.CXFService.IWSSerServicePortType;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-10-15T09:21:04.166+08:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "IWSSerService",
                  wsdlLocation = "http://10.71.32.117:8080/zftal-mobile/service/IWSSerService?wsdl",
                  targetNamespace = "http://service.cxf.webservices.mobile.zfsoft.com/")
public class IWSSerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.webservices.mobile.zfsoft.com/", "IWSSerService");
    public final static QName IWSSerServiceHttpPort = new QName("http://service.cxf.webservices.mobile.zfsoft.com/", "IWSSerServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.71.32.117:8080/zftal-mobile/service/IWSSerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IWSSerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.71.32.117:8080/zftal-mobile/service/IWSSerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IWSSerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IWSSerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWSSerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
/*    public IWSSerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }*/

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
  /*  public IWSSerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }*/

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
 /*   public IWSSerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     *
     * @return
     *     returns IWSSerServicePortType
     */
    @WebEndpoint(name = "IWSSerServiceHttpPort")
    public IWSSerServicePortType getIWSSerServiceHttpPort() {
        return super.getPort(IWSSerServiceHttpPort, IWSSerServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSSerServicePortType
     */
    @WebEndpoint(name = "IWSSerServiceHttpPort")
    public IWSSerServicePortType getIWSSerServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(IWSSerServiceHttpPort, IWSSerServicePortType.class, features);
    }

}
