package com.zfsoft.mobile.services.assetWebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-11-03T11:39:49.612+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://qufeisoft.com/webservices/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    @WebResult(name = "getLastNoticeListResult", targetNamespace = "http://qufeisoft.com/webservices/")
    @RequestWrapper(localName = "getLastNoticeList", targetNamespace = "http://qufeisoft.com/webservices/", className = "com.zfsoft.mobile.services.assetWebservice.GetLastNoticeList")
    @WebMethod(action = "http://qufeisoft.com/webservices/getLastNoticeList")
    @ResponseWrapper(localName = "getLastNoticeListResponse", targetNamespace = "http://qufeisoft.com/webservices/", className = "com.zfsoft.mobile.services.assetWebservice.GetLastNoticeListResponse")
    public java.lang.String getLastNoticeList(
        @WebParam(name = "yhm", targetNamespace = "http://qufeisoft.com/webservices/")
        java.lang.String yhm,
        @WebParam(name = "noticeType", targetNamespace = "http://qufeisoft.com/webservices/")
        java.lang.String noticeType,
        @WebParam(name = "num", targetNamespace = "http://qufeisoft.com/webservices/")
        int num,
        @WebParam(name = "sign", targetNamespace = "http://qufeisoft.com/webservices/")
        java.lang.String sign
    );

    @WebResult(name = "getLastTodoTaskListResult", targetNamespace = "http://qufeisoft.com/webservices/")
    @RequestWrapper(localName = "getLastTodoTaskList", targetNamespace = "http://qufeisoft.com/webservices/", className = "com.zfsoft.mobile.services.assetWebservice.GetLastTodoTaskList")
    @WebMethod(action = "http://qufeisoft.com/webservices/getLastTodoTaskList")
    @ResponseWrapper(localName = "getLastTodoTaskListResponse", targetNamespace = "http://qufeisoft.com/webservices/", className = "com.zfsoft.mobile.services.assetWebservice.GetLastTodoTaskListResponse")
    public java.lang.String getLastTodoTaskList(
        @WebParam(name = "yhm", targetNamespace = "http://qufeisoft.com/webservices/")
        java.lang.String yhm,
        @WebParam(name = "num", targetNamespace = "http://qufeisoft.com/webservices/")
        int num,
        @WebParam(name = "sign", targetNamespace = "http://qufeisoft.com/webservices/")
        java.lang.String sign
    );
}
