package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.728+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IClassPeriodTime")
@XmlSeeAlso({ObjectFactory.class})
public interface IClassPeriodTime {

    @WebResult(name = "ClassPeriodTimeInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IClassPeriodTime/ClassPeriodTimeInfo", output = "http://tempuri.org/IClassPeriodTime/ClassPeriodTimeInfoResponse")
    @RequestWrapper(localName = "ClassPeriodTimeInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ClassPeriodTimeInfo")
    @WebMethod(operationName = "ClassPeriodTimeInfo", action = "http://tempuri.org/IClassPeriodTime/ClassPeriodTimeInfo")
    @ResponseWrapper(localName = "ClassPeriodTimeInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ClassPeriodTimeInfoResponse")
    public java.lang.String classPeriodTimeInfo(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
