package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.728+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IClassRoom")
@XmlSeeAlso({ObjectFactory.class})
public interface IClassRoom {

    @WebResult(name = "ClassRoomCategoryInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IClassRoom/ClassRoomCategoryInfo", output = "http://tempuri.org/IClassRoom/ClassRoomCategoryInfoResponse")
    @RequestWrapper(localName = "ClassRoomCategoryInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ClassRoomCategoryInfo")
    @WebMethod(operationName = "ClassRoomCategoryInfo", action = "http://tempuri.org/IClassRoom/ClassRoomCategoryInfo")
    @ResponseWrapper(localName = "ClassRoomCategoryInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ClassRoomCategoryInfoResponse")
    public java.lang.String classRoomCategoryInfo();

    @WebResult(name = "GetClassroomListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IClassRoom/GetClassroomList", output = "http://tempuri.org/IClassRoom/GetClassroomListResponse")
    @RequestWrapper(localName = "GetClassroomList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetClassroomList")
    @WebMethod(operationName = "GetClassroomList", action = "http://tempuri.org/IClassRoom/GetClassroomList")
    @ResponseWrapper(localName = "GetClassroomListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetClassroomListResponse")
    public java.lang.String getClassroomList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "TeachingSiteInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IClassRoom/TeachingSiteInfo", output = "http://tempuri.org/IClassRoom/TeachingSiteInfoResponse")
    @RequestWrapper(localName = "TeachingSiteInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeachingSiteInfo")
    @WebMethod(operationName = "TeachingSiteInfo", action = "http://tempuri.org/IClassRoom/TeachingSiteInfo")
    @ResponseWrapper(localName = "TeachingSiteInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeachingSiteInfoResponse")
    public java.lang.String teachingSiteInfo();

    @WebResult(name = "TeachingSiteIdleInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IClassRoom/TeachingSiteIdleInfo", output = "http://tempuri.org/IClassRoom/TeachingSiteIdleInfoResponse")
    @RequestWrapper(localName = "TeachingSiteIdleInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeachingSiteIdleInfo")
    @WebMethod(operationName = "TeachingSiteIdleInfo", action = "http://tempuri.org/IClassRoom/TeachingSiteIdleInfo")
    @ResponseWrapper(localName = "TeachingSiteIdleInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeachingSiteIdleInfoResponse")
    public java.lang.String teachingSiteIdleInfo(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "role", targetNamespace = "http://tempuri.org/")
        java.lang.String role,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
