package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.743+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IConfigurationInfo")
@XmlSeeAlso({ObjectFactory.class})
public interface IConfigurationInfo {

    @WebResult(name = "GetZZCJKResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IConfigurationInfo/GetZZCJK", output = "http://tempuri.org/IConfigurationInfo/GetZZCJKResponse")
    @RequestWrapper(localName = "GetZZCJK", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetZZCJK")
    @WebMethod(operationName = "GetZZCJK", action = "http://tempuri.org/IConfigurationInfo/GetZZCJK")
    @ResponseWrapper(localName = "GetZZCJKResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetZZCJKResponse")
    public java.lang.String getZZCJK(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetKXDYTJKResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IConfigurationInfo/GetKXDYTJK", output = "http://tempuri.org/IConfigurationInfo/GetKXDYTJKResponse")
    @RequestWrapper(localName = "GetKXDYTJK", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetKXDYTJK")
    @WebMethod(operationName = "GetKXDYTJK", action = "http://tempuri.org/IConfigurationInfo/GetKXDYTJK")
    @ResponseWrapper(localName = "GetKXDYTJKResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetKXDYTJKResponse")
    public java.lang.String getKXDYTJK(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "ConfigurationInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IConfigurationInfo/ConfigurationInfo", output = "http://tempuri.org/IConfigurationInfo/ConfigurationInfoResponse")
    @RequestWrapper(localName = "ConfigurationInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ConfigurationInfo")
    @WebMethod(operationName = "ConfigurationInfo", action = "http://tempuri.org/IConfigurationInfo/ConfigurationInfo")
    @ResponseWrapper(localName = "ConfigurationInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ConfigurationInfoResponse")
    public java.lang.String configurationInfo();
}
