package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.759+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ICourseTask")
@XmlSeeAlso({ObjectFactory.class})
public interface ICourseTask {

    @WebResult(name = "GetClassListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetClassList", output = "http://tempuri.org/ICourseTask/GetClassListResponse")
    @RequestWrapper(localName = "GetClassList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetClassList")
    @WebMethod(operationName = "GetClassList", action = "http://tempuri.org/ICourseTask/GetClassList")
    @ResponseWrapper(localName = "GetClassListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetClassListResponse")
    public java.lang.String getClassList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetYearTermListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetYearTermList", output = "http://tempuri.org/ICourseTask/GetYearTermListResponse")
    @RequestWrapper(localName = "GetYearTermList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetYearTermList")
    @WebMethod(operationName = "GetYearTermList", action = "http://tempuri.org/ICourseTask/GetYearTermList")
    @ResponseWrapper(localName = "GetYearTermListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetYearTermListResponse")
    public java.lang.String getYearTermList(
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count
    );

    @WebResult(name = "CourseTaskInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/CourseTaskInfo", output = "http://tempuri.org/ICourseTask/CourseTaskInfoResponse")
    @RequestWrapper(localName = "CourseTaskInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseTaskInfo")
    @WebMethod(operationName = "CourseTaskInfo", action = "http://tempuri.org/ICourseTask/CourseTaskInfo")
    @ResponseWrapper(localName = "CourseTaskInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseTaskInfoResponse")
    public java.lang.String courseTaskInfo(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetCourseListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetCourseList", output = "http://tempuri.org/ICourseTask/GetCourseListResponse")
    @RequestWrapper(localName = "GetCourseList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetCourseList")
    @WebMethod(operationName = "GetCourseList", action = "http://tempuri.org/ICourseTask/GetCourseList")
    @ResponseWrapper(localName = "GetCourseListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetCourseListResponse")
    public java.lang.String getCourseList(
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count
    );

    @WebResult(name = "GetTeacherListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetTeacherList", output = "http://tempuri.org/ICourseTask/GetTeacherListResponse")
    @RequestWrapper(localName = "GetTeacherList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetTeacherList")
    @WebMethod(operationName = "GetTeacherList", action = "http://tempuri.org/ICourseTask/GetTeacherList")
    @ResponseWrapper(localName = "GetTeacherListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetTeacherListResponse")
    public java.lang.String getTeacherList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetGradeListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetGradeList", output = "http://tempuri.org/ICourseTask/GetGradeListResponse")
    @RequestWrapper(localName = "GetGradeList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetGradeList")
    @WebMethod(operationName = "GetGradeList", action = "http://tempuri.org/ICourseTask/GetGradeList")
    @ResponseWrapper(localName = "GetGradeListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetGradeListResponse")
    public java.lang.String getGradeList(
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count
    );

    @WebResult(name = "GetMajorListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetMajorList", output = "http://tempuri.org/ICourseTask/GetMajorListResponse")
    @RequestWrapper(localName = "GetMajorList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetMajorList")
    @WebMethod(operationName = "GetMajorList", action = "http://tempuri.org/ICourseTask/GetMajorList")
    @ResponseWrapper(localName = "GetMajorListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetMajorListResponse")
    public java.lang.String getMajorList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetInstituteListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetInstituteList", output = "http://tempuri.org/ICourseTask/GetInstituteListResponse")
    @RequestWrapper(localName = "GetInstituteList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetInstituteList")
    @WebMethod(operationName = "GetInstituteList", action = "http://tempuri.org/ICourseTask/GetInstituteList")
    @ResponseWrapper(localName = "GetInstituteListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetInstituteListResponse")
    public java.lang.String getInstituteList(
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count
    );

    @WebResult(name = "CourseTaskSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/CourseTaskSearch", output = "http://tempuri.org/ICourseTask/CourseTaskSearchResponse")
    @RequestWrapper(localName = "CourseTaskSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseTaskSearch")
    @WebMethod(operationName = "CourseTaskSearch", action = "http://tempuri.org/ICourseTask/CourseTaskSearch")
    @ResponseWrapper(localName = "CourseTaskSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseTaskSearchResponse")
    public java.lang.String courseTaskSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetCourseList1Result", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetCourseList1", output = "http://tempuri.org/ICourseTask/GetCourseList1Response")
    @RequestWrapper(localName = "GetCourseList1", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetCourseList1")
    @WebMethod(operationName = "GetCourseList1", action = "http://tempuri.org/ICourseTask/GetCourseList1")
    @ResponseWrapper(localName = "GetCourseList1Response", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetCourseList1Response")
    public java.lang.String getCourseList1(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetMajorFieldListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetMajorFieldList", output = "http://tempuri.org/ICourseTask/GetMajorFieldListResponse")
    @RequestWrapper(localName = "GetMajorFieldList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetMajorFieldList")
    @WebMethod(operationName = "GetMajorFieldList", action = "http://tempuri.org/ICourseTask/GetMajorFieldList")
    @ResponseWrapper(localName = "GetMajorFieldListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetMajorFieldListResponse")
    public java.lang.String getMajorFieldList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GetStudentListResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/GetStudentList", output = "http://tempuri.org/ICourseTask/GetStudentListResponse")
    @RequestWrapper(localName = "GetStudentList", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetStudentList")
    @WebMethod(operationName = "GetStudentList", action = "http://tempuri.org/ICourseTask/GetStudentList")
    @ResponseWrapper(localName = "GetStudentListResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GetStudentListResponse")
    public java.lang.String getStudentList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "CourseJxdgInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/CourseJxdgInfo", output = "http://tempuri.org/ICourseTask/CourseJxdgInfoResponse")
    @RequestWrapper(localName = "CourseJxdgInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseJxdgInfo")
    @WebMethod(operationName = "CourseJxdgInfo", action = "http://tempuri.org/ICourseTask/CourseJxdgInfo")
    @ResponseWrapper(localName = "CourseJxdgInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseJxdgInfoResponse")
    public java.lang.String courseJxdgInfo(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "CourseJxdgTextInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ICourseTask/CourseJxdgTextInfo", output = "http://tempuri.org/ICourseTask/CourseJxdgTextInfoResponse")
    @RequestWrapper(localName = "CourseJxdgTextInfo", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseJxdgTextInfo")
    @WebMethod(operationName = "CourseJxdgTextInfo", action = "http://tempuri.org/ICourseTask/CourseJxdgTextInfo")
    @ResponseWrapper(localName = "CourseJxdgTextInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.CourseJxdgTextInfoResponse")
    public java.lang.String courseJxdgTextInfo(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
