package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.681+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IExamArrange")
@XmlSeeAlso({ObjectFactory.class})
public interface IExamArrange {

    @WebResult(name = "MakeUpExamArrangeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IExamArrange/MakeUpExamArrange", output = "http://tempuri.org/IExamArrange/MakeUpExamArrangeResponse")
    @RequestWrapper(localName = "MakeUpExamArrange", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.MakeUpExamArrange")
    @WebMethod(operationName = "MakeUpExamArrange", action = "http://tempuri.org/IExamArrange/MakeUpExamArrange")
    @ResponseWrapper(localName = "MakeUpExamArrangeResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.MakeUpExamArrangeResponse")
    public java.lang.String makeUpExamArrange(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GraduationMakeUpExamArrangeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IExamArrange/GraduationMakeUpExamArrange", output = "http://tempuri.org/IExamArrange/GraduationMakeUpExamArrangeResponse")
    @RequestWrapper(localName = "GraduationMakeUpExamArrange", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GraduationMakeUpExamArrange")
    @WebMethod(operationName = "GraduationMakeUpExamArrange", action = "http://tempuri.org/IExamArrange/GraduationMakeUpExamArrange")
    @ResponseWrapper(localName = "GraduationMakeUpExamArrangeResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GraduationMakeUpExamArrangeResponse")
    public java.lang.String graduationMakeUpExamArrange(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "ExamArrangeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IExamArrange/ExamArrange", output = "http://tempuri.org/IExamArrange/ExamArrangeResponse")
    @RequestWrapper(localName = "ExamArrange", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ExamArrange")
    @WebMethod(operationName = "ExamArrange", action = "http://tempuri.org/IExamArrange/ExamArrange")
    @ResponseWrapper(localName = "ExamArrangeResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ExamArrangeResponse")
    public java.lang.String examArrange(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
