package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.759+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IScoreSearch")
@XmlSeeAlso({ObjectFactory.class})
public interface IScoreSearch {

    @WebResult(name = "ScoreInfoSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IScoreSearch/ScoreInfoSearch", output = "http://tempuri.org/IScoreSearch/ScoreInfoSearchResponse")
    @RequestWrapper(localName = "ScoreInfoSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreInfoSearch")
    @WebMethod(operationName = "ScoreInfoSearch", action = "http://tempuri.org/IScoreSearch/ScoreInfoSearch")
    @ResponseWrapper(localName = "ScoreInfoSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreInfoSearchResponse")
    public java.lang.String scoreInfoSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "GradeScoreInfoSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IScoreSearch/GradeScoreInfoSearch", output = "http://tempuri.org/IScoreSearch/GradeScoreInfoSearchResponse")
    @RequestWrapper(localName = "GradeScoreInfoSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GradeScoreInfoSearch")
    @WebMethod(operationName = "GradeScoreInfoSearch", action = "http://tempuri.org/IScoreSearch/GradeScoreInfoSearch")
    @ResponseWrapper(localName = "GradeScoreInfoSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.GradeScoreInfoSearchResponse")
    public java.lang.String gradeScoreInfoSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "ScoreInfoSearch2Result", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IScoreSearch/ScoreInfoSearch2", output = "http://tempuri.org/IScoreSearch/ScoreInfoSearch2Response")
    @RequestWrapper(localName = "ScoreInfoSearch2", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreInfoSearch2")
    @WebMethod(operationName = "ScoreInfoSearch2", action = "http://tempuri.org/IScoreSearch/ScoreInfoSearch2")
    @ResponseWrapper(localName = "ScoreInfoSearch2Response", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreInfoSearch2Response")
    public java.lang.String scoreInfoSearch2(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "ScoreSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IScoreSearch/ScoreSearch", output = "http://tempuri.org/IScoreSearch/ScoreSearchResponse")
    @RequestWrapper(localName = "ScoreSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreSearch")
    @WebMethod(operationName = "ScoreSearch", action = "http://tempuri.org/IScoreSearch/ScoreSearch")
    @ResponseWrapper(localName = "ScoreSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.ScoreSearchResponse")
    public java.lang.String scoreSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
