package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.790+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ITeacherSuperviseArrangement")
@XmlSeeAlso({ObjectFactory.class})
public interface ITeacherSuperviseArrangement {

    @WebResult(name = "TeacherSuperviseArrangementSearch1Result", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearch1", output = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearch1Response")
    @RequestWrapper(localName = "TeacherSuperviseArrangementSearch1", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherSuperviseArrangementSearch1")
    @WebMethod(operationName = "TeacherSuperviseArrangementSearch1", action = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearch1")
    @ResponseWrapper(localName = "TeacherSuperviseArrangementSearch1Response", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherSuperviseArrangementSearch1Response")
    public java.lang.String teacherSuperviseArrangementSearch1(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "TeacherSuperviseArrangementSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearch", output = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearchResponse")
    @RequestWrapper(localName = "TeacherSuperviseArrangementSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherSuperviseArrangementSearch")
    @WebMethod(operationName = "TeacherSuperviseArrangementSearch", action = "http://tempuri.org/ITeacherSuperviseArrangement/TeacherSuperviseArrangementSearch")
    @ResponseWrapper(localName = "TeacherSuperviseArrangementSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherSuperviseArrangementSearchResponse")
    public java.lang.String teacherSuperviseArrangementSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
