package com.zfsoft.jw.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-08-07T16:52:16.728+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ITeacherInfo")
@XmlSeeAlso({ObjectFactory.class})
public interface ITeacherInfo {

    @WebResult(name = "TeacherInfoSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ITeacherInfo/TeacherInfoSearch", output = "http://tempuri.org/ITeacherInfo/TeacherInfoSearchResponse")
    @RequestWrapper(localName = "TeacherInfoSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherInfoSearch")
    @WebMethod(operationName = "TeacherInfoSearch", action = "http://tempuri.org/ITeacherInfo/TeacherInfoSearch")
    @ResponseWrapper(localName = "TeacherInfoSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherInfoSearchResponse")
    public java.lang.String teacherInfoSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        java.lang.String count,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );

    @WebResult(name = "TeacherPhotosSearchResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ITeacherInfo/TeacherPhotosSearch", output = "http://tempuri.org/ITeacherInfo/TeacherPhotosSearchResponse")
    @RequestWrapper(localName = "TeacherPhotosSearch", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherPhotosSearch")
    @WebMethod(operationName = "TeacherPhotosSearch", action = "http://tempuri.org/ITeacherInfo/TeacherPhotosSearch")
    @ResponseWrapper(localName = "TeacherPhotosSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.jw.org.tempuri.TeacherPhotosSearchResponse")
    public byte[] teacherPhotosSearch(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        java.lang.String parameterList,
        @WebParam(name = "strKey", targetNamespace = "http://tempuri.org/")
        java.lang.String strKey
    );
}
