
package com.zfsoft.keyan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-31T15:38:13.517+08:00
 * Generated source version: 3.2.4
 *
 */
public final class IRepairInfoMobileService_IRepairInfoMobileServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.hq.portal.webservice.zfsoft.com/", "IRepairInfoMobileServiceService");

    private IRepairInfoMobileService_IRepairInfoMobileServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IRepairInfoMobileServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        IRepairInfoMobileServiceService ss = new IRepairInfoMobileServiceService(wsdlURL, SERVICE_NAME);
        IRepairInfoMobileService port = ss.getIRepairInfoMobileServicePort();

        {
        System.out.println("Invoking submitRepair...");
        java.lang.String _submitRepair_arg0 = "";
        java.lang.String _submitRepair_arg1 = "";
        java.lang.String _submitRepair_arg2 = "";
        java.lang.String _submitRepair_arg3 = "";
        java.lang.String _submitRepair_arg4 = "";
        java.lang.String _submitRepair_arg5 = "";
        java.lang.String _submitRepair_arg6 = "";
        java.lang.String _submitRepair_arg7 = "";
        java.lang.String _submitRepair_arg8 = "";
        java.lang.String _submitRepair__return = port.submitRepair(_submitRepair_arg0, _submitRepair_arg1, _submitRepair_arg2, _submitRepair_arg3, _submitRepair_arg4, _submitRepair_arg5, _submitRepair_arg6, _submitRepair_arg7, _submitRepair_arg8);
        System.out.println("submitRepair.result=" + _submitRepair__return);


        }
        {
        System.out.println("Invoking getMobieRepairList...");
        java.lang.String _getMobieRepairList_arg0 = "";
        java.lang.String _getMobieRepairList_arg1 = "";
        java.lang.String _getMobieRepairList_arg2 = "";
        java.lang.String _getMobieRepairList_arg3 = "";
        java.lang.String _getMobieRepairList__return = port.getMobieRepairList(_getMobieRepairList_arg0, _getMobieRepairList_arg1, _getMobieRepairList_arg2, _getMobieRepairList_arg3);
        System.out.println("getMobieRepairList.result=" + _getMobieRepairList__return);


        }
        {
        System.out.println("Invoking getMobieRepairType...");
        java.lang.String _getMobieRepairType_arg0 = "";
        java.lang.String _getMobieRepairType_arg1 = "";
        java.lang.String _getMobieRepairType__return = port.getMobieRepairType(_getMobieRepairType_arg0, _getMobieRepairType_arg1);
        System.out.println("getMobieRepairType.result=" + _getMobieRepairType__return);


        }
        {
        System.out.println("Invoking getRepairAddress...");
        java.lang.String _getRepairAddress_arg0 = "";
        java.lang.String _getRepairAddress_arg1 = "";
        java.lang.String _getRepairAddress__return = port.getRepairAddress(_getRepairAddress_arg0, _getRepairAddress_arg1);
        System.out.println("getRepairAddress.result=" + _getRepairAddress__return);


        }

        System.exit(0);
    }

}
