
package com.zfsoft.keyan;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-31T15:38:13.551+08:00
 * Generated source version: 3.2.4
 *
 */

public class IRepairInfoMobileService_IRepairInfoMobileServicePort_Server{

    protected IRepairInfoMobileService_IRepairInfoMobileServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IRepairInfoMobileServicePortImpl();
        String address = "http://10.71.33.70:8089/zfwebservice/repairInfoMobileService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new IRepairInfoMobileService_IRepairInfoMobileServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
