
package com.zfsoft.versionVerify.CXFServe;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.zfsoft.versionVerify.CXFServe.imp.VersionVerifyXmlServiceService;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-16T11:51:36.890+08:00
 * Generated source version: 2.6.0
 *
 */
public final class IVersionVerifyXmlService_VersionVerifyXmlServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://imp.service.version.webservice.general.zfsoft.com/", "VersionVerifyXmlServiceService");

    private IVersionVerifyXmlService_VersionVerifyXmlServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VersionVerifyXmlServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VersionVerifyXmlServiceService ss = new VersionVerifyXmlServiceService(wsdlURL, SERVICE_NAME);
        IVersionVerifyXmlService port = ss.getVersionVerifyXmlServicePort();

        {
        System.out.println("Invoking versionCompare...");
        java.lang.String _versionCompare_imei = "";
        java.lang.String _versionCompare_imsi = "";
        java.lang.String _versionCompare_sysinfo = "";
        java.lang.String _versionCompare_ua = "";
        java.lang.String _versionCompare_phonum = "";
        java.lang.String _versionCompare_account = "";
        java.lang.String _versionCompare_v = "";
        java.lang.String _versionCompare__return = port.versionCompare(_versionCompare_imei, _versionCompare_imsi, _versionCompare_sysinfo, _versionCompare_ua, _versionCompare_phonum, _versionCompare_account, _versionCompare_v);
        System.out.println("versionCompare.result=" + _versionCompare__return);


        }

        System.exit(0);
    }

}
