
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zfsoft.backMh.introduce.CXFServe.service;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-05T14:44:16.250+08:00
 * Generated source version: 2.5.2
 *
 */

@javax.jws.WebService(
                      serviceName = "IntroduceXmlServiceService",
                      portName = "IntroduceXmlServicePort",
                      targetNamespace = "http://service.introduce.logic.webservice.general.zfsoft.com/",
                      wsdlLocation = "http://10.71.19.191:9992/zfmcmh/webservices/introduce/IntroduceXmlService?wsdl",
                      endpointInterface = "com.backMh.introduce.CXFServe.service.IIntroduceXmlService")

public class IIntroduceXmlServiceImpl implements IIntroduceXmlService {

    private static final Logger LOG = Logger.getLogger(IIntroduceXmlServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.introduce.service.IIntroduceXmlService#getChildIntroduceTypeList(java.lang.String  id ,)int  start ,)int  size )*
     */
    public java.lang.String getChildIntroduceTypeList(java.lang.String id,int start,int size) {
        LOG.info("Executing operation getChildIntroduceTypeList");
        System.out.println(id);
        System.out.println(start);
        System.out.println(size);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.introduce.service.IIntroduceXmlService#getRootIntroduceTypeList(*
     */
    public java.lang.String getRootIntroduceTypeList() {
        LOG.info("Executing operation getRootIntroduceTypeList");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.introduce.service.IIntroduceXmlService#getIntroduceByTypeId(java.lang.String  tid )*
     */
    public java.lang.String getIntroduceByTypeId(java.lang.String tid) {
        LOG.info("Executing operation getIntroduceByTypeId");
        System.out.println(tid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    /* (non-Javadoc)
     * @see com.zfsoft.general.webservice.logic.introduce.service.IIntroduceXmlService#getChildIntroduceTypeListAddPid(java.lang.String  id ,)int  start ,)int  size )*
     */
    public java.lang.String getChildIntroduceTypeListAddPid(java.lang.String id,int start,int size) {
        LOG.info("Executing operation getChildIntroduceTypeListAddPid");
        System.out.println(id);
        System.out.println(start);
        System.out.println(size);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
