
package com.zfsoft.backMh.news.CXFService.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T09:49:02.187+08:00
 * Generated source version: 2.5.2
 *
 */

public class INewsXmlService_NewsXmlServicePort_Server{

    protected INewsXmlService_NewsXmlServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new INewsXmlServiceImpl();
        String address = "http://10.71.19.191:9992/zfmcmh/webservices/news/NewsXmlService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new INewsXmlService_NewsXmlServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
