package com.zfsoft.xg.lx.CXFService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-10-30T14:46:50.988+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://service.lx.xgws.zfsoft.com/", name = "ILxService")
@XmlSeeAlso({ObjectFactory.class})
public interface ILxService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLxdxmshxxList", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetLxdxmshxxList")
    @WebMethod
    @ResponseWrapper(localName = "getLxdxmshxxListResponse", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetLxdxmshxxListResponse")
    public java.lang.String getLxdxmshxxList(
        @WebParam(name = "yhm", targetNamespace = "")
        java.lang.String yhm,
        @WebParam(name = "num", targetNamespace = "")
        java.lang.Integer num,
        @WebParam(name = "PAGE", targetNamespace = "")
        java.lang.String page,
        @WebParam(name = "sign", targetNamespace = "")
        java.lang.String sign
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTzggDetail", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetTzggDetail")
    @WebMethod
    @ResponseWrapper(localName = "getTzggDetailResponse", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetTzggDetailResponse")
    public java.lang.String getTzggDetail(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "yhm", targetNamespace = "")
        java.lang.String yhm,
        @WebParam(name = "sign", targetNamespace = "")
        java.lang.String sign
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLxTzggList", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetLxTzggList")
    @WebMethod
    @ResponseWrapper(localName = "getLxTzggListResponse", targetNamespace = "http://service.lx.xgws.zfsoft.com/", className = "com.xg.lx.CXFService.GetLxTzggListResponse")
    public java.lang.String getLxTzggList(
        @WebParam(name = "yhlx", targetNamespace = "")
        java.lang.String yhlx,
        @WebParam(name = "num", targetNamespace = "")
        java.lang.Integer num,
        @WebParam(name = "yhm", targetNamespace = "")
        java.lang.String yhm,
        @WebParam(name = "sign", targetNamespace = "")
        java.lang.String sign,
        @WebParam(name = "pageIndex", targetNamespace = "")
        java.lang.Integer pageIndex
    );
}
