package com.zfsoft.xg.xg.CXFService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-08-03T14:21:21.080+08:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "XtwhServiceImplService",
                  wsdlLocation = "http://10.71.33.152:8088/zfxgws/xgxt/xtwhService?wsdl",
                  targetNamespace = "http://impl.xtwh.xgxt.ws.xgxtws.zfsoft.com/")
public class XtwhServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.xtwh.xgxt.ws.xgxtws.zfsoft.com/", "XtwhServiceImplService");
    public final static QName XtwhServiceImplPort = new QName("http://impl.xtwh.xgxt.ws.xgxtws.zfsoft.com/", "XtwhServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.71.33.152:8088/zfxgws/xgxt/xtwhService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XtwhServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.71.33.152:8088/zfxgws/xgxt/xtwhService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XtwhServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XtwhServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XtwhServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XtwhServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XtwhServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XtwhServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns XtwhService
     */
    @WebEndpoint(name = "XtwhServiceImplPort")
    public XtwhService getXtwhServiceImplPort() {
        return super.getPort(XtwhServiceImplPort, XtwhService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XtwhService
     */
    @WebEndpoint(name = "XtwhServiceImplPort")
    public XtwhService getXtwhServiceImplPort(WebServiceFeature... features) {
        return super.getPort(XtwhServiceImplPort, XtwhService.class, features);
    }

}
