package com.zfsoft.backMh.version.CXFService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:28:22.312+08:00
 * Generated source version: 2.5.2
 *
 */
@WebService(targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", name = "IVersionXmlService")
@XmlSeeAlso({ObjectFactory.class})
public interface IVersionXmlService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "decode", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.Decode")
    @WebMethod
    @ResponseWrapper(localName = "decodeResponse", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.DecodeResponse")
    public java.lang.String decode(
        @WebParam(name = "code", targetNamespace = "")
        java.lang.String code
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkVersion", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.CheckVersion")
    @WebMethod
    @ResponseWrapper(localName = "checkVersionResponse", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.CheckVersionResponse")
    public java.lang.String checkVersion(
        @WebParam(name = "imei", targetNamespace = "")
        java.lang.String imei,
        @WebParam(name = "imsi", targetNamespace = "")
        java.lang.String imsi,
        @WebParam(name = "sysinfo", targetNamespace = "")
        java.lang.String sysinfo,
        @WebParam(name = "ua", targetNamespace = "")
        java.lang.String ua,
        @WebParam(name = "phonum", targetNamespace = "")
        java.lang.String phonum,
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "v", targetNamespace = "")
        java.lang.String v
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "encode", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.Encode")
    @WebMethod
    @ResponseWrapper(localName = "encodeResponse", targetNamespace = "http://service.version.sys.webservice.general.zfsoft.com/", className = "com.backMh.version.CXFService.service.EncodeResponse")
    public java.lang.String encode(
        @WebParam(name = "code", targetNamespace = "")
        java.lang.String code
    );
}
