
package com.zfsoft.backMh.version.CXFService.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:28:22.312+08:00
 * Generated source version: 2.5.2
 *
 */

public class IVersionXmlService_VersionXmlServicePort_Server{

    protected IVersionXmlService_VersionXmlServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IVersionXmlServiceImpl();
        String address = "http://10.71.19.191:9992/zfmcmh/webservices/version/VersionXmlService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new IVersionXmlService_VersionXmlServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
