
package com.zfsoft.backMh.version.CXFService.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.zfsoft.backMh.version.CXFService.service.imp.VersionXmlServiceService;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:28:22.281+08:00
 * Generated source version: 2.5.2
 *
 */
public final class IVersionXmlService_VersionXmlServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.version.sys.webservice.general.zfsoft.com/", "VersionXmlServiceService");

    private IVersionXmlService_VersionXmlServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VersionXmlServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VersionXmlServiceService ss = new VersionXmlServiceService(wsdlURL, SERVICE_NAME);
        IVersionXmlService port = ss.getVersionXmlServicePort();

        {
        System.out.println("Invoking decode...");
        java.lang.String _decode_code = "";
        java.lang.String _decode__return = port.decode(_decode_code);
        System.out.println("decode.result=" + _decode__return);


        }
        {
        System.out.println("Invoking checkVersion...");
        java.lang.String _checkVersion_imei = "";
        java.lang.String _checkVersion_imsi = "";
        java.lang.String _checkVersion_sysinfo = "";
        java.lang.String _checkVersion_ua = "";
        java.lang.String _checkVersion_phonum = "";
        java.lang.String _checkVersion_account = "";
        java.lang.String _checkVersion_v = "";
        java.lang.String _checkVersion__return = port.checkVersion(_checkVersion_imei, _checkVersion_imsi, _checkVersion_sysinfo, _checkVersion_ua, _checkVersion_phonum, _checkVersion_account, _checkVersion_v);
        System.out.println("checkVersion.result=" + _checkVersion__return);


        }
        {
        System.out.println("Invoking encode...");
        java.lang.String _encode_code = "";
        java.lang.String _encode__return = port.encode(_encode_code);
        System.out.println("encode.result=" + _encode__return);


        }

        System.exit(0);
    }

}
