package com.zfsoft.backMh.schoolsights.CXFService.service.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.zfsoft.backMh.schoolsights.CXFService.service.ISchoolsightsXmlService;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-06T11:09:42.468+08:00
 * Generated source version: 2.5.2
 *
 */
@WebServiceClient(name = "SchoolsightsXmlServiceService",
                  wsdlLocation = "http://10.71.19.191:9992/zfmcmh/webservices/schoolsights/SchoolsightsXmlService?wsdl",
                  targetNamespace = "http://service.schoolsights.logic.webservice.general.zfsoft.com/")
public class SchoolsightsXmlServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.schoolsights.logic.webservice.general.zfsoft.com/", "SchoolsightsXmlServiceService");
    public final static QName SchoolsightsXmlServicePort = new QName("http://service.schoolsights.logic.webservice.general.zfsoft.com/", "SchoolsightsXmlServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.71.19.191:9992/zfmcmh/webservices/schoolsights/SchoolsightsXmlService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SchoolsightsXmlServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.71.19.191:9992/zfmcmh/webservices/schoolsights/SchoolsightsXmlService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SchoolsightsXmlServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SchoolsightsXmlServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchoolsightsXmlServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns ISchoolsightsXmlService
     */
    @WebEndpoint(name = "SchoolsightsXmlServicePort")
    public ISchoolsightsXmlService getSchoolsightsXmlServicePort() {
        return super.getPort(SchoolsightsXmlServicePort, ISchoolsightsXmlService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISchoolsightsXmlService
     */
    @WebEndpoint(name = "SchoolsightsXmlServicePort")
    public ISchoolsightsXmlService getSchoolsightsXmlServicePort(WebServiceFeature... features) {
        return super.getPort(SchoolsightsXmlServicePort, ISchoolsightsXmlService.class, features);
    }

}
