
package com.zfsoft.oa.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2018-09-18T15:03:39.930+08:00
 * Generated source version: 2.6.0
 *
 */

public class IOaMobileService_OaMobileServiceImplPort_Server{

    protected IOaMobileService_OaMobileServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IOaMobileServiceImpl();
        String address = "http://10.71.33.61:8081/zfwebservice/ws/oaMobileService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new IOaMobileService_OaMobileServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
