
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zfsoft.oa.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-10T10:51:07.175+08:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "OaMobileServiceImplService",
                      portName = "OaMobileServiceImplPort",
                      targetNamespace = "http://impl.service.oa.portal.webservice.zfsoft.com/",
                      wsdlLocation = "http://10.71.33.61:8081/zfwebservice/ws/oaMobileService?wsdl",
                      endpointInterface = "com.oa.service.IOaMobileService")

public class OaMobileServiceImplPortImpl implements IOaMobileService {

    private static final Logger LOG = Logger.getLogger(OaMobileServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getXmAndDepByMobiletel(java.lang.String yhm, java.lang.String mobiletel, java.lang.String sign)*
     */
    public java.lang.String getXmAndDepByMobiletel(java.lang.String yhm, java.lang.String mobiletel, java.lang.String sign) {
        LOG.info("Executing operation getXmAndDepByMobiletel");
        System.out.println(yhm);
        System.out.println(mobiletel);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMailInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String getMailInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation getMailInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateZwByID(java.lang.String yhm, java.lang.String id, byte[] data, java.lang.String sign)*
     */
    public java.lang.String updateZwByID(java.lang.String yhm, java.lang.String id, byte[] data, java.lang.String sign) {
        LOG.info("Executing operation updateZwByID");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(data);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDepAndUserByDepNum(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String sum, java.lang.String sign)*
     */
    public java.lang.String getDepAndUserByDepNum(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String sum, java.lang.String sign) {
        LOG.info("Executing operation getDepAndUserByDepNum");
        System.out.println(yhm);
        System.out.println(depnum);
        System.out.println(depname);
        System.out.println(sum);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNoticeListAndCond(java.lang.String yhm, java.lang.String type, java.lang.String check, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getNoticeListAndCond(java.lang.String yhm, java.lang.String type, java.lang.String check, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getNoticeListAndCond");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(check);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#excuTaskForFlow(java.lang.String yhm, java.lang.String id, java.lang.String taskId, java.lang.String sign)*
     */
    public java.lang.String excuTaskForFlow(java.lang.String yhm, java.lang.String id, java.lang.String taskId, java.lang.String sign) {
        LOG.info("Executing operation excuTaskForFlow");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(taskId);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#checkLogin(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String checkLogin(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation checkLogin");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDepAndUserInfoForSearchForHttp(java.lang.String yhm, java.lang.String name, java.lang.String sign)*
     */
    public java.lang.String getDepAndUserInfoForSearchForHttp(java.lang.String yhm, java.lang.String name, java.lang.String sign) {
        LOG.info("Executing operation getDepAndUserInfoForSearchForHttp");
        System.out.println(yhm);
        System.out.println(name);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getStuFirstDepInfo(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getStuFirstDepInfo(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getStuFirstDepInfo");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWeekWork(java.lang.String yhm, java.lang.String time, java.lang.String sign)*
     */
    public java.lang.String getWeekWork(java.lang.String yhm, java.lang.String time, java.lang.String sign) {
        LOG.info("Executing operation getWeekWork");
        System.out.println(yhm);
        System.out.println(time);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getSharePerson(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getSharePerson(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getSharePerson");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcyCgxList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getWjcyCgxList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getWjcyCgxList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNewMailCount(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getNewMailCount(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getNewMailCount");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#saveGzrzb(java.lang.String yhm, java.lang.String rznr, java.lang.String rq, java.lang.String sign)*
     */
    public java.lang.String saveGzrzb(java.lang.String yhm, java.lang.String rznr, java.lang.String rq, java.lang.String sign) {
        LOG.info("Executing operation saveGzrzb");
        System.out.println(yhm);
        System.out.println(rznr);
        System.out.println(rq);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#deleteSchedule(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String deleteSchedule(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation deleteSchedule");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getZxgwList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getZxgwList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getZxgwList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getScheduleInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getScheduleInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getScheduleInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getSignKey(java.lang.String key)*
     */
    public java.lang.String getSignKey(java.lang.String key) {
        LOG.info("Executing operation getSignKey");
        System.out.println(key);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#saveWjcyZf(java.lang.String yhm, java.lang.String id, java.lang.String zfyj, java.lang.String zfdx, java.lang.String yxqx, java.lang.String sign)*
     */
    public java.lang.String saveWjcyZf(java.lang.String yhm, java.lang.String id, java.lang.String zfyj, java.lang.String zfdx, java.lang.String yxqx, java.lang.String sign) {
        LOG.info("Executing operation saveWjcyZf");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(zfyj);
        System.out.println(zfdx);
        System.out.println(yxqx);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#fjUploadByType(java.lang.String yhm, java.lang.String zid, java.lang.String wjmc, java.lang.String fileType, com.zfsoft.oa.service.FileModel data, java.lang.String sign)*
     */
    public java.lang.String fjUploadByType(java.lang.String yhm, java.lang.String zid, java.lang.String wjmc, java.lang.String fileType, FileModel data, java.lang.String sign) {
        LOG.info("Executing operation fjUploadByType");
        System.out.println(yhm);
        System.out.println(zid);
        System.out.println(wjmc);
        System.out.println(fileType);
        System.out.println(data);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#saveToDraft(java.lang.String yjid, java.lang.String yhm, java.lang.String fsrxm, java.lang.String sjrxm, java.lang.String sjrdm, java.lang.String csrxm, java.lang.String csrdm, java.lang.String title, java.lang.String content, java.lang.String sign)*
     */
    public java.lang.String saveToDraft(java.lang.String yjid, java.lang.String yhm, java.lang.String fsrxm, java.lang.String sjrxm, java.lang.String sjrdm, java.lang.String csrxm, java.lang.String csrdm, java.lang.String title, java.lang.String content, java.lang.String sign) {
        LOG.info("Executing operation saveToDraft");
        System.out.println(yjid);
        System.out.println(yhm);
        System.out.println(fsrxm);
        System.out.println(sjrxm);
        System.out.println(sjrdm);
        System.out.println(csrxm);
        System.out.println(csrdm);
        System.out.println(title);
        System.out.println(content);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doSubmitFlowone(java.lang.String yhm, java.lang.String id, java.lang.String nextid, java.lang.String nextuser, java.lang.String comment, java.lang.String tablename, java.lang.String ftzd, java.lang.String ftfs, java.lang.String zid, java.lang.String sign)*
     */
    public java.lang.String doSubmitFlowone(java.lang.String yhm, java.lang.String id, java.lang.String nextid, java.lang.String nextuser, java.lang.String comment, java.lang.String tablename, java.lang.String ftzd, java.lang.String ftfs, java.lang.String zid, java.lang.String sign) {
        LOG.info("Executing operation doSubmitFlowone");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(nextid);
        System.out.println(nextuser);
        System.out.println(comment);
        System.out.println(tablename);
        System.out.println(ftzd);
        System.out.println(ftfs);
        System.out.println(zid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getScheduleList(java.lang.String yhm, java.lang.String yhid, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getScheduleList(java.lang.String yhm, java.lang.String yhid, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getScheduleList");
        System.out.println(yhm);
        System.out.println(yhid);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getZxgwInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String getZxgwInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation getZxgwInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getStuClassByType(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String type, java.lang.String sum, java.lang.String sign)*
     */
    public java.lang.String getStuClassByType(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String type, java.lang.String sum, java.lang.String sign) {
        LOG.info("Executing operation getStuClassByType");
        System.out.println(yhm);
        System.out.println(depnum);
        System.out.println(depname);
        System.out.println(type);
        System.out.println(sum);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getTableInfo(java.lang.String yhm, java.lang.String id, java.lang.String tablename, java.lang.String sign)*
     */
    public java.lang.String getTableInfo(java.lang.String yhm, java.lang.String id, java.lang.String tablename, java.lang.String sign) {
        LOG.info("Executing operation getTableInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(tablename);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMessageCount(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getMessageCount(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getMessageCount");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNewConferenceList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getNewConferenceList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getNewConferenceList");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getFileString(java.lang.String id)*
     */
    public java.lang.String getFileString(java.lang.String id) {
        LOG.info("Executing operation getFileString");
        System.out.println(id);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNoticeInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getNoticeInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getNoticeInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#addSchedule(java.lang.String yhm, java.lang.String zt, java.lang.String date, java.lang.String starttime, java.lang.String endtime, java.lang.String content, java.lang.String sign)*
     */
    public java.lang.String addSchedule(java.lang.String yhm, java.lang.String zt, java.lang.String date, java.lang.String starttime, java.lang.String endtime, java.lang.String content, java.lang.String sign) {
        LOG.info("Executing operation addSchedule");
        System.out.println(yhm);
        System.out.println(zt);
        System.out.println(date);
        System.out.println(starttime);
        System.out.println(endtime);
        System.out.println(content);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#setZxwgQf(java.lang.String yhm, java.lang.String eid, java.lang.String qsyj, java.lang.String sign)*
     */
    public java.lang.String setZxwgQf(java.lang.String yhm, java.lang.String eid, java.lang.String qsyj, java.lang.String sign) {
        LOG.info("Executing operation setZxwgQf");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(qsyj);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#sendMail(java.lang.String yjid, java.lang.String yhm, java.lang.String fsrxm, java.lang.String sjrxm, java.lang.String sjrdm, java.lang.String csrxm, java.lang.String csrdm, java.lang.String title, java.lang.String content, java.lang.String type, java.lang.String sign)*
     */
    public java.lang.String sendMail(java.lang.String yjid, java.lang.String yhm, java.lang.String fsrxm, java.lang.String sjrxm, java.lang.String sjrdm, java.lang.String csrxm, java.lang.String csrdm, java.lang.String title, java.lang.String content, java.lang.String type, java.lang.String sign) {
        LOG.info("Executing operation sendMail");
        System.out.println(yjid);
        System.out.println(yhm);
        System.out.println(fsrxm);
        System.out.println(sjrxm);
        System.out.println(sjrdm);
        System.out.println(csrxm);
        System.out.println(csrdm);
        System.out.println(title);
        System.out.println(content);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcyCgxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String getWjcyCgxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation getWjcyCgxInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getLclxList(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getLclxList(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getLclxList");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getLdhyhdList(java.lang.String yhm, java.lang.String kssj, java.lang.String jssj, java.lang.String sign)*
     */
    public java.lang.String getLdhyhdList(java.lang.String yhm, java.lang.String kssj, java.lang.String jssj, java.lang.String sign) {
        LOG.info("Executing operation getLdhyhdList");
        System.out.println(yhm);
        System.out.println(kssj);
        System.out.println(jssj);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#sendPtdx(java.lang.String fromsender, java.lang.String toSender, java.lang.String title, java.lang.String messageContent)*
     */
    public java.lang.String sendPtdx(java.lang.String fromsender, java.lang.String toSender, java.lang.String title, java.lang.String messageContent) {
        LOG.info("Executing operation sendPtdx");
        System.out.println(fromsender);
        System.out.println(toSender);
        System.out.println(title);
        System.out.println(messageContent);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNoticeList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getNoticeList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getNoticeList");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateMailXbByID(java.lang.String yhm, java.lang.String id, java.lang.String type, java.lang.String sign)*
     */
    public java.lang.String updateMailXbByID(java.lang.String yhm, java.lang.String id, java.lang.String type, java.lang.String sign) {
        LOG.info("Executing operation updateMailXbByID");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDepAndUserByDepNumForHttp(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String sum, java.lang.String sign)*
     */
    public java.lang.String getDepAndUserByDepNumForHttp(java.lang.String yhm, java.lang.String depnum, java.lang.String depname, java.lang.String sum, java.lang.String sign) {
        LOG.info("Executing operation getDepAndUserByDepNumForHttp");
        System.out.println(yhm);
        System.out.println(depnum);
        System.out.println(depname);
        System.out.println(sum);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateCurrentSectionFiled(java.lang.String yhm, java.lang.String id, java.lang.String tableName, java.lang.String paramJson, java.lang.String sign)*
     */
    public java.lang.String updateCurrentSectionFiled(java.lang.String yhm, java.lang.String id, java.lang.String tableName, java.lang.String paramJson, java.lang.String sign) {
        LOG.info("Executing operation updateCurrentSectionFiled");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(tableName);
        System.out.println(paramJson);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doBackBefore(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String doBackBefore(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation doBackBefore");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#deleteMailByID(java.lang.String yhm, java.lang.String eid, java.lang.String type, java.lang.String sign)*
     */
    public java.lang.String deleteMailByID(java.lang.String yhm, java.lang.String eid, java.lang.String type, java.lang.String sign) {
        LOG.info("Executing operation deleteMailByID");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getFirstDepInfoForHttp(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getFirstDepInfoForHttp(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getFirstDepInfoForHttp");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getAddressInfo(java.lang.String yhm, java.lang.String yhid, java.lang.String sign)*
     */
    public java.lang.String getAddressInfo(java.lang.String yhm, java.lang.String yhid, java.lang.String sign) {
        LOG.info("Executing operation getAddressInfo");
        System.out.println(yhm);
        System.out.println(yhid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateWorkDiaryZt(java.lang.String yhm, java.lang.String id, java.lang.String rzzt, java.lang.String sign)*
     */
    public java.lang.String updateWorkDiaryZt(java.lang.String yhm, java.lang.String id, java.lang.String rzzt, java.lang.String sign) {
        LOG.info("Executing operation updateWorkDiaryZt");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(rzzt);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateWorkDiary(java.lang.String yhm, java.lang.String id, java.lang.String content, java.lang.String sign)*
     */
    public java.lang.String updateWorkDiary(java.lang.String yhm, java.lang.String id, java.lang.String content, java.lang.String sign) {
        LOG.info("Executing operation updateWorkDiary");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(content);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcyFjxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String getWjcyFjxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation getWjcyFjxInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doSubmitBefore(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String doSubmitBefore(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation doSubmitBefore");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getTodoTaskListBySfyb(java.lang.String yhm, java.lang.String sfyb, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getTodoTaskListBySfyb(java.lang.String yhm, java.lang.String sfyb, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getTodoTaskListBySfyb");
        System.out.println(yhm);
        System.out.println(sfyb);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getAddressList(java.lang.String yhm, java.lang.String cxlx, java.lang.String sign)*
     */
    public java.lang.String getAddressList(java.lang.String yhm, java.lang.String cxlx, java.lang.String sign) {
        LOG.info("Executing operation getAddressList");
        System.out.println(yhm);
        System.out.println(cxlx);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMessageList(java.lang.String yhm, java.lang.String messageZt, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getMessageList(java.lang.String yhm, java.lang.String messageZt, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getMessageList");
        System.out.println(yhm);
        System.out.println(messageZt);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getTodoTaskList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getTodoTaskList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getTodoTaskList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getNoticType(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getNoticType(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getNoticType");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getSoluteTaskList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getSoluteTaskList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getSoluteTaskList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doBackBeforeByReturnNode(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String doBackBeforeByReturnNode(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation doBackBeforeByReturnNode");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#saveConferenceInformfeedback(java.lang.String id, java.lang.String yhm, java.lang.String conferenceid, java.lang.String reason, java.lang.String ispresent, java.lang.String time, java.lang.String sign)*
     */
    public java.lang.String saveConferenceInformfeedback(java.lang.String id, java.lang.String yhm, java.lang.String conferenceid, java.lang.String reason, java.lang.String ispresent, java.lang.String time, java.lang.String sign) {
        LOG.info("Executing operation saveConferenceInformfeedback");
        System.out.println(id);
        System.out.println(yhm);
        System.out.println(conferenceid);
        System.out.println(reason);
        System.out.println(ispresent);
        System.out.println(time);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getLdapGh(java.lang.String email, java.lang.String pw)*
     */
    public java.lang.String getLdapGh(java.lang.String email, java.lang.String pw) {
        LOG.info("Executing operation getLdapGh");
        System.out.println(email);
        System.out.println(pw);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateMailByID(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String updateMailByID(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation updateMailByID");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWorkDiaryList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getWorkDiaryList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getWorkDiaryList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMeetNoticeInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getMeetNoticeInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getMeetNoticeInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#addWorkDiary(java.lang.String yhm, java.lang.String content, java.lang.String date, java.lang.String type, java.lang.String sign)*
     */
    public java.lang.String addWorkDiary(java.lang.String yhm, java.lang.String content, java.lang.String date, java.lang.String type, java.lang.String sign) {
        LOG.info("Executing operation addWorkDiary");
        System.out.println(yhm);
        System.out.println(content);
        System.out.println(date);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getFirstDepInfo(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getFirstDepInfo(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getFirstDepInfo");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getShareWorkDiaryList(java.lang.String yhm, java.lang.String shareperson, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getShareWorkDiaryList(java.lang.String yhm, java.lang.String shareperson, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getShareWorkDiaryList");
        System.out.println(yhm);
        System.out.println(shareperson);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doSubmitFlow(java.lang.String yhm, java.lang.String id, java.lang.String nextid, java.lang.String nextuser, java.lang.String comment, java.lang.String sign)*
     */
    public java.lang.String doSubmitFlow(java.lang.String yhm, java.lang.String id, java.lang.String nextid, java.lang.String nextuser, java.lang.String comment, java.lang.String sign) {
        LOG.info("Executing operation doSubmitFlow");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(nextid);
        System.out.println(nextuser);
        System.out.println(comment);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcySjxSlById(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getWjcySjxSlById(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getWjcySjxSlById");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getSendInfo(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getSendInfo(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getSendInfo");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDoneTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getDoneTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getDoneTaskListByConditionAndLx");
        System.out.println(yhm);
        System.out.println(condition);
        System.out.println(lxid);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#confirmWjcy(java.lang.String yhm, java.lang.String id, java.lang.String nr, java.lang.String sign)*
     */
    public java.lang.String confirmWjcy(java.lang.String yhm, java.lang.String id, java.lang.String nr, java.lang.String sign) {
        LOG.info("Executing operation confirmWjcy");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(nr);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#delWorkDiary(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String delWorkDiary(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation delWorkDiary");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getLdcyyjbList(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getLdcyyjbList(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getLdcyyjbList");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getLdhyhdInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getLdhyhdInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getLdhyhdInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcyFjxList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getWjcyFjxList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getWjcyFjxList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doBackFlow(java.lang.String yhm, java.lang.String id, java.lang.String comment, java.lang.String sign)*
     */
    public java.lang.String doBackFlow(java.lang.String yhm, java.lang.String id, java.lang.String comment, java.lang.String sign) {
        LOG.info("Executing operation doBackFlow");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(comment);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#updateWjcyZt(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String updateWjcyZt(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation updateWjcyZt");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcySjxList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getWjcySjxList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getWjcySjxList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWorkType(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getWorkType(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getWorkType");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getZfNewFj(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getZfNewFj(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getZfNewFj");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMailListByTypeAndCond(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String cond, java.lang.String sign)*
     */
    public java.lang.String getMailListByTypeAndCond(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String cond, java.lang.String sign) {
        LOG.info("Executing operation getMailListByTypeAndCond");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(cond);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getConferenceNoticeList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getConferenceNoticeList(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getConferenceNoticeList");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getConferenceNoticeListAndCond(java.lang.String yhm, java.lang.String type, java.lang.String check, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getConferenceNoticeListAndCond(java.lang.String yhm, java.lang.String type, java.lang.String check, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getConferenceNoticeListAndCond");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(check);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#sendSjdx(java.lang.String fromsender, java.lang.String toSender, java.lang.String messageContent)*
     */
    public java.lang.String sendSjdx(java.lang.String fromsender, java.lang.String toSender, java.lang.String messageContent) {
        LOG.info("Executing operation sendSjdx");
        System.out.println(fromsender);
        System.out.println(toSender);
        System.out.println(messageContent);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDepAndUserInfoForSearch(java.lang.String yhm, java.lang.String name, java.lang.String sign)*
     */
    public java.lang.String getDepAndUserInfoForSearch(java.lang.String yhm, java.lang.String name, java.lang.String sign) {
        LOG.info("Executing operation getDepAndUserInfoForSearch");
        System.out.println(yhm);
        System.out.println(name);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getConferenceInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getConferenceInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getConferenceInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMeetNoticeList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getMeetNoticeList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getMeetNoticeList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getCurrentSectionFiled(java.lang.String yhm, java.lang.String id, java.lang.String tableName, java.lang.String zid, java.lang.String sign)*
     */
    public java.lang.String getCurrentSectionFiled(java.lang.String yhm, java.lang.String id, java.lang.String tableName, java.lang.String zid, java.lang.String sign) {
        LOG.info("Executing operation getCurrentSectionFiled");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(tableName);
        System.out.println(zid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getGzrzList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getGzrzList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getGzrzList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getTodoTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getTodoTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getTodoTaskListByConditionAndLx");
        System.out.println(yhm);
        System.out.println(condition);
        System.out.println(lxid);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDraftInfoById(java.lang.String yhm, java.lang.String yjid, java.lang.String sign)*
     */
    public java.lang.String getDraftInfoById(java.lang.String yhm, java.lang.String yjid, java.lang.String sign) {
        LOG.info("Executing operation getDraftInfoById");
        System.out.println(yhm);
        System.out.println(yjid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getFileModel(java.lang.String id)*
     */
    public com.zfsoft.oa.service.FileModel getFileModel(java.lang.String id) {
        LOG.info("Executing operation getFileModel");
        System.out.println(id);
        try {
            com.zfsoft.oa.service.FileModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWjcySjxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign)*
     */
    public java.lang.String getWjcySjxInfoById(java.lang.String yhm, java.lang.String eid, java.lang.String sign) {
        LOG.info("Executing operation getWjcySjxInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getDoneTaskList(java.lang.String yhm, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getDoneTaskList(java.lang.String yhm, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getDoneTaskList");
        System.out.println(yhm);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWorkForWeek(java.lang.String yhm, int num, java.lang.String sign)*
     */
    public java.lang.String getWorkForWeek(java.lang.String yhm, int num, java.lang.String sign) {
        LOG.info("Executing operation getWorkForWeek");
        System.out.println(yhm);
        System.out.println(num);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#checkPassword(java.lang.String yhm, java.lang.String flowPassword, java.lang.String sign)*
     */
    public java.lang.String checkPassword(java.lang.String yhm, java.lang.String flowPassword, java.lang.String sign) {
        LOG.info("Executing operation checkPassword");
        System.out.println(yhm);
        System.out.println(flowPassword);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getMailListByType(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getMailListByType(java.lang.String yhm, java.lang.String type, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getMailListByType");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getFlowInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign)*
     */
    public java.lang.String getFlowInfo(java.lang.String yhm, java.lang.String id, java.lang.String sign) {
        LOG.info("Executing operation getFlowInfo");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#addTempWorkDiary(java.lang.String yhm, java.lang.String content, java.lang.String date, java.lang.String type, java.lang.String sign)*
     */
    public java.lang.String addTempWorkDiary(java.lang.String yhm, java.lang.String content, java.lang.String date, java.lang.String type, java.lang.String sign) {
        LOG.info("Executing operation addTempWorkDiary");
        System.out.println(yhm);
        System.out.println(content);
        System.out.println(date);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getWorkDiarySharePerson(java.lang.String yhm, java.lang.String sign)*
     */
    public java.lang.String getWorkDiarySharePerson(java.lang.String yhm, java.lang.String sign) {
        LOG.info("Executing operation getWorkDiarySharePerson");
        System.out.println(yhm);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#getSoluteTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign)*
     */
    public java.lang.String getSoluteTaskListByConditionAndLx(java.lang.String yhm, java.lang.String condition, java.lang.String lxid, int start, int size, java.lang.String sign) {
        LOG.info("Executing operation getSoluteTaskListByConditionAndLx");
        System.out.println(yhm);
        System.out.println(condition);
        System.out.println(lxid);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zfsoft.oa.service.IOaMobileService#doBackFlowByReturnNode(java.lang.String yhm, java.lang.String id, java.lang.String returnNode, java.lang.String returnSfsfh, java.lang.String comment, java.lang.String sign)*
     */
    public java.lang.String doBackFlowByReturnNode(java.lang.String yhm, java.lang.String id, java.lang.String returnNode, java.lang.String returnSfsfh, java.lang.String comment, java.lang.String sign) {
        LOG.info("Executing operation doBackFlowByReturnNode");
        System.out.println(yhm);
        System.out.println(id);
        System.out.println(returnNode);
        System.out.println(returnSfsfh);
        System.out.println(comment);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }



	@Override
	public String getFfwjList(String yhm, String type, int start, int size,
			String sign) {
		LOG.info("Executing operation getFfwjList");
        System.out.println(yhm);
        System.out.println(type);
        System.out.println(start);
        System.out.println(size);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
	}

	@Override
	public String getZxgwInfoById(String yhm, String eid, String type,
			String sign) {
		LOG.info("Executing operation getZxgwInfoById");
        System.out.println(yhm);
        System.out.println(eid);
        System.out.println(type);
        System.out.println(sign);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
	}

}
