package com.zfsoft.newmobile.LibService.CXFService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2016-06-13T18:55:21.392+08:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://service.ws.hw.com/", name = "LibServiceDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface LibServiceDelegate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLendHist", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetLendHist")
    @WebMethod
    @ResponseWrapper(localName = "getLendHistResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetLendHistResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Circ> getLendHist(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "exceedFine", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.ExceedFine")
    @WebMethod
    @ResponseWrapper(localName = "exceedFineResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.ExceedFineResponse")
    public void exceedFine(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReader", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetReader")
    @WebMethod
    @ResponseWrapper(localName = "getReaderResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetReaderResponse")
    public com.zfsoft.newmobile.LibService.CXFService.Reader getReader(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.LogoutResponse")
    public int logout(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRedrTypes", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRedrTypes")
    @WebMethod
    @ResponseWrapper(localName = "getRedrTypesResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRedrTypesResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.SimpleBean> getRedrTypes(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "voltFine", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.VoltFine")
    @WebMethod
    @ResponseWrapper(localName = "voltFineResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.VoltFineResponse")
    public void voltFine(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        float arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.lang.String arg10
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPregs", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetPregs")
    @WebMethod
    @ResponseWrapper(localName = "getPregsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetPregsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Preg> getPregs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "certLoss", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.CertLoss")
    @WebMethod
    @ResponseWrapper(localName = "certLossResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.CertLossResponse")
    public void certLoss(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLostPays", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetLostPays")
    @WebMethod
    @ResponseWrapper(localName = "getLostPaysResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetLostPaysResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.LostPay> getLostPays(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetBook")
    @WebMethod
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetBookResponse")
    public com.zfsoft.newmobile.LibService.CXFService.Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getViolations", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetViolations")
    @WebMethod
    @ResponseWrapper(localName = "getViolationsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetViolationsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Violation> getViolations(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeps", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetDeps")
    @WebMethod
    @ResponseWrapper(localName = "getDepsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetDepsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.SimpleBean> getDeps(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkReader", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.CheckReader")
    @WebMethod
    @ResponseWrapper(localName = "checkReaderResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.CheckReaderResponse")
    public com.zfsoft.newmobile.LibService.CXFService.CheckRedrResult checkReader(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getItems", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetItems")
    @WebMethod
    @ResponseWrapper(localName = "getItemsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetItemsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Item> getItems(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPregArrivals", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetPregArrivals")
    @WebMethod
    @ResponseWrapper(localName = "getPregArrivalsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetPregArrivalsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Arrival> getPregArrivals(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetAccounts")
    @WebMethod
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetAccountsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Account> getAccounts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "exceedFine1", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.ExceedFine1")
    @WebMethod
    @ResponseWrapper(localName = "exceedFine1Response", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.ExceedFine1Response")
    public void exceedFine1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        float arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        int arg10
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "registerReader", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.RegisterReader")
    @WebMethod
    @ResponseWrapper(localName = "registerReaderResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.RegisterReaderResponse")
    public void registerReader(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.lang.String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        java.lang.String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        java.lang.String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        java.lang.String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        java.lang.String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        java.lang.String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        java.lang.String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        java.lang.String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        java.lang.String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        java.lang.String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        java.lang.String arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        java.lang.String arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        java.lang.String arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        java.lang.String arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        java.lang.String arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        java.lang.String arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        java.lang.String arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        java.lang.String arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        java.lang.String arg28
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRelegateArrivals", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRelegateArrivals")
    @WebMethod
    @ResponseWrapper(localName = "getRelegateArrivalsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRelegateArrivalsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Arrival> getRelegateArrivals(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRelegates", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRelegates")
    @WebMethod
    @ResponseWrapper(localName = "getRelegatesResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetRelegatesResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Relegate> getRelegates(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getViolations1", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetViolations1")
    @WebMethod
    @ResponseWrapper(localName = "getViolations1Response", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetViolations1Response")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Violation> getViolations1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDebts", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetDebts")
    @WebMethod
    @ResponseWrapper(localName = "getDebtsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetDebtsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Debt> getDebts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMarc", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetMarc")
    @WebMethod
    @ResponseWrapper(localName = "getMarcResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetMarcResponse")
    public com.zfsoft.newmobile.LibService.CXFService.Marc getMarc(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCircs", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetCircs")
    @WebMethod
    @ResponseWrapper(localName = "getCircsResponse", targetNamespace = "http://service.ws.hw.com/", className = "com.zfsoft.newmobile.LibService.CXFService.GetCircsResponse")
    public java.util.List<com.zfsoft.newmobile.LibService.CXFService.Circ> getCircs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws NoAuthorityException_Exception, SystemException_Exception;
}
