package com.zfsoft.backMh.schoolintroduce.CXFServe.service.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.zfsoft.backMh.schoolintroduce.CXFServe.service.ISIntroduceXmlService;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-01-21T13:47:33.140+08:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "SIntroduceXmlServiceService",
                  wsdlLocation = "http://localhost:8888/zfmmh_manager/webservices/sIntroduce/SIntroduceXmlService?wsdl",
                  targetNamespace = "http://impl.service.schoolintroduce.logic.webservice.general.zfsoft.com/")
public class SIntroduceXmlServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.schoolintroduce.logic.webservice.general.zfsoft.com/", "SIntroduceXmlServiceService");
    public final static QName SIntroduceXmlServicePort = new QName("http://impl.service.schoolintroduce.logic.webservice.general.zfsoft.com/", "SIntroduceXmlServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/zfmmh_manager/webservices/sIntroduce/SIntroduceXmlService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIntroduceXmlServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/zfmmh_manager/webservices/sIntroduce/SIntroduceXmlService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIntroduceXmlServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIntroduceXmlServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIntroduceXmlServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns ISIntroduceXmlService
     */
    @WebEndpoint(name = "SIntroduceXmlServicePort")
    public ISIntroduceXmlService getSIntroduceXmlServicePort() {
        return super.getPort(SIntroduceXmlServicePort, ISIntroduceXmlService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISIntroduceXmlService
     */
    @WebEndpoint(name = "SIntroduceXmlServicePort")
    public ISIntroduceXmlService getSIntroduceXmlServicePort(WebServiceFeature... features) {
        return super.getPort(SIntroduceXmlServicePort, ISIntroduceXmlService.class, features);
    }

}
